HTTP task 1 finished
js-tasks-ru/nodejs-20210315_cherevaty-nik pull request #4
Opened 2021-06-21 21:53 UTC by Mykytyi

2021-06-21 21:54 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-06-22 07:50 UTC, RidgeA requested changes

2021-06-22 07:50 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +          const file = fs.createReadStream(filepath);
Необходимо подписаться на событие `error` у стрима на чтение. 
Т.к. эти операции асинхронны, то ошибка не будет обработана в `catch` блоке

2021-06-22 21:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-22 21:51 UTC, Mykytyi commented on 05-http-server-streams/01-file-server-get/server.js
> +          const file = fs.createReadStream(filepath);
Точно
Добавил обработчик

2021-06-22 21:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2021-06-23 07:07 UTC, RidgeA approved these changes

2021-06-23 07:07 UTC, merged